version: "3.8"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: scraper-backend
    environment:
      - DOCKER_CONTAINER=true
    env_file: ./backend/.env       # ใส่ UPSTASH_REDIS_REST_URL และ TOKEN
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: scraper-frontend
    environment:
      NEXT_PUBLIC_API_URL: "http://localhost:8000"  # ปรับให้ชี้ backend
    ports:
      - "3000:3000"
